/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module smoketest(clk, rst, a, b, y, q);
  input a;
  wire a;
  input b;
  wire b;
  input clk;
  wire clk;
  output q;
  reg q;
  input rst;
  wire rst;
  output y;
  wire y;
  assign y = b & a;
  always @(posedge clk)
    if (rst) q <= 1'h0;
    else q <= y;
endmodule
